### ISSUE TITLE
Change notification's scrolling

### ISSUE THREAD

**Issue by SMore-Napi** [InnoQueue/Mobile#8]
There should be a single scrolling on the screen. 
- First elements - `unread`notifications
- Other elements - `all`notifications

**They shouldn't be separated**

**Comment by SMore-Napi** [comment]
Thanks to Timur! 

2787df4bab3beab92142446b2ba5084581ca1b94

**Comment by al1ych** [comment]
Done
2787df4bab3beab92142446b2ba5084581ca1b94
